apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base/performance

resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - performance.openshift.io_performanceprofiles_crd.yaml
  - performance-addon-operator.v0.0.1.clusterserviceversion.yaml

patchesStrategicMerge:
  - performance_profile.patch.yaml
