---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: performance-operator
rules:
- apiGroups:
  - performance.openshift.io
  resources:
  - performanceprofiles
  - performanceprofiles/finalizers
  - performanceprofiles/status
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - featuregates
  verbs:
  - '*'
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - machineconfigs
  - machineconfigpools
  - kubeletconfigs
  verbs:
  - '*'
- apiGroups:
  - tuned.openshift.io
  resources:
  - tuneds
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: openshift-performance-addon
  name: performance-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - configmaps
  - events
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - apps
  resourceNames:
  - performance-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - '*'
