apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - machine_config_pool.yaml
  - operator_namespace.yaml
  - operator_operatorgroup.yaml
  - operator_catalogsource.yaml
  - operator_subscription.yaml
