apiVersion: apps/v1
kind: Deployment
metadata:
  name: performance-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: performance-operator
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        name: performance-operator
    spec:
      serviceAccountName: performance-operator
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
        - name: performance-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - performance-operator
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "performance-operator"
  install:
    spec:
      clusterPermissions:
