apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: example-performanceprofile
spec:
  cpu:
    isolated: "1-3"
    nonIsolated: "0"
    reserved: "0"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 2
  realTimeKernel:
    enabled: true
  nodeSelector:
    node-role.kubernetes.io/worker-rt: ""
