apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: ci
spec:
  cpu:
    isolated: "1-3"
    reserved: "0"
  hugepages:
    pages:
    - size: "1G"
      count: 1
      node: 0
  nodeSelector:
    node-role.kubernetes.io/worker-rt: ""
