// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUPerformanceProfile) DeepCopyInto(out *CPUPerformanceProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUPerformanceProfile.
func (in *CPUPerformanceProfile) DeepCopy() *CPUPerformanceProfile {
	if in == nil {
		return nil
	}
	out := new(CPUPerformanceProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CPUPerformanceProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUPerformanceProfileList) DeepCopyInto(out *CPUPerformanceProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CPUPerformanceProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUPerformanceProfileList.
func (in *CPUPerformanceProfileList) DeepCopy() *CPUPerformanceProfileList {
	if in == nil {
		return nil
	}
	out := new(CPUPerformanceProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CPUPerformanceProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUPerformanceProfileSpec) DeepCopyInto(out *CPUPerformanceProfileSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUPerformanceProfileSpec.
func (in *CPUPerformanceProfileSpec) DeepCopy() *CPUPerformanceProfileSpec {
	if in == nil {
		return nil
	}
	out := new(CPUPerformanceProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUPerformanceProfileStatus) DeepCopyInto(out *CPUPerformanceProfileStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUPerformanceProfileStatus.
func (in *CPUPerformanceProfileStatus) DeepCopy() *CPUPerformanceProfileStatus {
	if in == nil {
		return nil
	}
	out := new(CPUPerformanceProfileStatus)
	in.DeepCopyInto(out)
	return out
}
