---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "performance.openshift.io/v1",
          "kind": "PerformanceProfile",
          "metadata": {
            "name": "example-performanceprofile"
          },
          "spec": {
            "additionalKernelArgs": [
              "nmi_watchdog=0",
              "audit=0",
              "mce=off",
              "processor.max_cstate=1",
              "idle=poll",
              "intel_idle.max_cstate=0"
            ],
            "cpu": {
              "isolated": "2-3",
              "reserved": "0-1"
            },
            "hugepages": {
              "defaultHugepagesSize": "1G",
              "pages": [
                {
                  "count": 2,
                  "node": 0,
                  "size": "1G"
                }
              ]
            },
            "nodeSelector": {
              "node-role.kubernetes.io/performance": ""
            },
            "realTimeKernel": {
              "enabled": true
            }
          }
        }
      ]
    capabilities: Basic Install
    containerImage: quay.io/openshift-kni/performance-addon-operator:4.6-snapshot
    olm.skipRange: '>=4.5.0 <4.6.0'
  name: performance-addon-operator.v4.6.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: PerformanceProfile is the Schema for the performanceprofiles API.
      displayName: Performance Profile
      kind: PerformanceProfile
      name: performanceprofiles.performance.openshift.io
      version: v1
    - description: PerformanceProfile is the Schema for the performanceprofiles API.
      displayName: Performance Profile
      kind: PerformanceProfile
      name: performanceprofiles.performance.openshift.io
      version: v1alpha1
  description: |2-

    Performance Addon Operator provides the ability to enable advanced node performance tunings on a set of nodes.
  displayName: Performance Addon Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - '*'
        - apiGroups:
          - performance.openshift.io
          resources:
          - performanceprofiles
          - performanceprofiles/finalizers
          - performanceprofiles/status
          verbs:
          - '*'
        - apiGroups:
          - machineconfiguration.openshift.io
          resources:
          - machineconfigs
          - machineconfigpools
          - kubeletconfigs
          verbs:
          - '*'
        - apiGroups:
          - tuned.openshift.io
          resources:
          - tuneds
          verbs:
          - '*'
        - apiGroups:
          - node.k8s.io
          resources:
          - runtimeclasses
          verbs:
          - '*'
        serviceAccountName: performance-operator
      deployments:
      - name: performance-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: performance-operator
          strategy: {}
          template:
            metadata:
              annotations:
                target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
              labels:
                name: performance-operator
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: node-role.kubernetes.io/master
                        operator: Exists
              containers:
              - command:
                - performance-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: performance-operator
                image: quay.io/openshift-kni/performance-addon-operator:4.6-snapshot
                imagePullPolicy: Always
                name: performance-operator
                resources: {}
              serviceAccountName: performance-operator
              tolerations:
              - effect: NoSchedule
                key: node-role.kubernetes.io/master
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - configmaps
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resourceNames:
          - performance-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - '*'
        serviceAccountName: performance-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - numa
  - realtime
  - cpu pinning
  - hugepages
  links:
  - name: Source Code
    url: https://github.com/openshift-kni/performance-addon-operators
  maturity: alpha
  provider:
    name: Red Hat
  version: 4.6.0
