FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

ARG BIN_DIR=
ARG ASSETS_DIR=build/assets

ENV LANG=en_US.utf8

COPY ${ASSETS_DIR} /assets
COPY ${BIN_DIR}performance-addon-operators /usr/local/bin/performance-operator
USER 1001

ENTRYPOINT [ "/usr/local/bin/performance-operator" ]
