# see: https://github.com/operator-framework/operator-registry/blob/master/docs/design/operator-bundle.md
FROM scratch

# the channel name we settled for is "${MAJOR}.${MINOR}"
# 1. trivial to crosscheck with OCP version we target
# 2. Z-stream friendly
ARG CHANNEL=4.11
ARG ZVERSION=0
ARG OLM_SOURCE=build/_output/manifests

LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=performance-addon-operator
LABEL operators.operatorframework.io.bundle.channels.v1=${CHANNEL}
LABEL operators.operatorframework.io.bundle.channel.default.v1=$CHANNEL}

COPY ${OLM_SOURCE}/performance-addon-operator/${CHANNEL}.${ZVERSION}/ /
