FROM quay.io/openshift/origin-operator-registry:latest

COPY deploy/olm-catalog /registry/performance-addon-operator-catalog

# replaces performance-addon-operator image with the one built by openshift ci
RUN find /registry/performance-addon-operator-catalog/ -type f -exec sed -i "s|REPLACE_IMAGE|quay.io/openshift-kni/performance-addon-operator:v4.4|g" {} \; || :

# Initialize the database
RUN initializer --manifests /registry/performance-addon-operator-catalog --output bundles.db

# There are multiple binaries in the origin-operator-registry
# We want the registry-server
ENTRYPOINT ["registry-server"]
CMD ["--database", "bundles.db"]
