FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

ARG BIN_DIR=

ENV LANG=en_US.utf8

COPY ${BIN_DIR}performance-addon-operators /usr/local/bin/performance-operator
COPY ${BIN_DIR}performance-profile-creator /usr/local/bin/performance-profile-creator
USER 1001

ENTRYPOINT [ "/usr/local/bin/performance-operator" ]
